export function normalizeGptAds(input,sites,now=new Date()){
 if(!input||!['CNY','USD','EUR','GBP','HKD'].includes(input.currency))throw new Error('请提供已确认的广告币种');
 if(!sites.some(s=>s.domain===input.domain))throw new Error('推广网站不在网站清单中');
 if(typeof input.sourceFile!=='string'||!input.sourceFile.trim()||input.sourceFile.length>200)throw new Error('缺少导出文件名称');
 if(!Array.isArray(input.rows)||!input.rows.length||input.rows.length>10000)throw new Error('每日记录数量无效');
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(now),keys=new Set();
 const daily=input.rows.map(r=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||new Date(r.date+'T00:00:00Z').toISOString().slice(0,10)!==r.date||r.date>today)throw new Error('存在无效或未来日期');if(typeof r.campaign!=='string'||!r.campaign.trim()||r.campaign.length>200)throw new Error('广告系列名称无效');const key=r.date+':'+r.campaign.trim();if(keys.has(key))throw new Error('存在重复的每日广告系列记录');keys.add(key);for(const field of ['cost','clicks','impressions','conversions'])if(typeof r[field]!=='number'||!Number.isFinite(r[field])||r[field]<0)throw new Error('广告指标必须为非负数字');if(!Number.isInteger(r.clicks)||!Number.isInteger(r.impressions))throw new Error('点击和展示必须为整数');return {date:r.date,campaignId:'gpt:'+r.campaign.trim(),campaign:r.campaign.trim(),channel:'GPT_ADS',status:'IMPORTED',clicks:r.clicks,impressions:r.impressions,costMicros:Math.round(r.cost*1e6),conversions:r.conversions,domain:input.domain,spendScope:'website'}}).sort((a,b)=>a.date.localeCompare(b.date)||a.campaign.localeCompare(b.campaign));
 const total=daily.reduce((n,r)=>n+r.costMicros,0)/1e6;if(typeof input.expectedTotal!=='number'||Math.abs(total-input.expectedTotal)>.005)throw new Error('每日花费合计与导出汇总不一致');
 return {sourceFile:input.sourceFile.trim(),importedAt:now.toISOString(),mode:'manual_import',currency:input.currency,domain:input.domain,accountName:String(input.accountName||'GPT Ads').slice(0,100),start:daily[0].date,end:daily.at(-1).date,daily,total};
}
