import {collectGa4} from './google.js';
import {refreshDashboard} from './refresh.js';
import {syncLeadsSheet} from './sheet-leads.js';
import {validateLeads} from './leads.js';
const enc=new TextEncoder();
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
const unb64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
async function hmac(secret,text){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);return b64(await crypto.subtle.sign('HMAC',key,enc.encode(text)))}
async function equal(a,b){const aa=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(a))),bb=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(b)));let v=0;for(let i=0;i<aa.length;i++)v|=aa[i]^bb[i];return v===0}
async function session(request,env){try{const raw=request.headers.get('Cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('ouyee_session='))?.split('=')[1];if(!raw)return false;const [payload,sig]=raw.split('.');if(!payload||!sig||!await equal(sig,await hmac(env.SESSION_SECRET,payload)))return false;const data=JSON.parse(new TextDecoder().decode(unb64(payload)));return data.v===1&&data.exp>Date.now()}catch{return false}}
const secureCookie=(value,request,expire=false)=>`ouyee_session=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${expire?0:43200}${new URL(request.url).protocol==='https:'?'; Secure':''}`;
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function login(error='',status=200){return new Response(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>登录 · Ouyee-Dashboard</title><style>*{box-sizing:border-box}body{margin:0;font-family:Inter,-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;background:#f8fafc;color:#101828;display:grid;place-items:center;min-height:100vh;padding:24px}.box{width:400px;max-width:100%;background:white;border:1px solid #e4e7ec;border-radius:18px;padding:38px 32px;box-shadow:0 8px 40px #10182806}.login-brand{display:block;width:174px;height:64px;object-fit:contain;margin-bottom:25px}.logo{width:48px;height:48px;background:#ecf3ff;color:#465fff;border-radius:12px;display:grid;place-items:center;margin-bottom:25px;font-size:18px;font-weight:650}h1{font-size:24px;letter-spacing:-.7px;margin:0 0 12px}p{color:#98a2b3;font-size:13px;line-height:1.7;margin:0 0 28px}label{display:block;font-size:12px;color:#667085;margin-bottom:9px}input{width:100%;border:1px solid #d0d5dd;border-radius:8px;padding:12px 14px;font-size:15px;outline-color:#465fff;background:white}button{width:100%;border:0;border-radius:8px;background:#465fff;color:white;padding:13px;font-size:13px;font-weight:500;margin-top:18px;cursor:pointer}.error{color:#d92d20;font-size:12px;margin-top:12px}.foot{border-top:1px solid #f2f4f7;margin:28px 0 0;padding-top:20px;font-size:10px;color:#98a2b3}</style></head><body><section class="box"><img class="login-brand" src="/site-logos/ouyedisplay.com-brand.png" alt="Ouyee Logo" width="174" height="64"><h1>Ouyee-Dashboard</h1><p>网站运营中心<br>登录后查看流量、广告与真实询盘。</p><form method="POST" action="/login"><label for="password">访问密码</label><input id="password" name="password" type="password" required maxlength="256" autocomplete="current-password" placeholder="输入访问密码" autofocus><button type="submit">进入看板</button>${error?`<div class="error">${error}</div>`:''}</form><p class="foot">经营数据仅限已授权人员访问。</p></section></body></html>`,{status,headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'none'; img-src 'self'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'"}})}
async function body(request){const length=Number(request.headers.get('Content-Length')||0);if(length>2_100_000)throw new Error('文件过大，请控制在 2MB 以内');const text=await request.text();if(enc.encode(text).length>2_100_000)throw new Error('文件过大，请控制在 2MB 以内');return JSON.parse(text||'{}')}
async function leadStore(env,sites,force=false){const manual=await env.DASHBOARD_DATA.get('leads',{type:'json'})||{connected:false,rows:[]};if(!sites)return manual;const sheet=await syncLeadsSheet(env,sites,force);const ids=new Set(sheet.rows.map(r=>r.id));const rows=[...sheet.rows,...manual.rows.filter(r=>!ids.has(r.id))].sort((a,b)=>b.date.localeCompare(a.date));return{...sheet,connected:sheet.connected||manual.connected,rows,updatedAt:[sheet.updatedAt||'',manual.updatedAt||''].sort().at(-1),qualificationAvailable:sheet.qualificationAvailable||manual.rows.some(r=>r.status&&r.status!=='未标注')}}
export async function handle(context){const {request,env}=context;const url=new URL(request.url),path=url.pathname;
if(['/site-logos/ouyedisplay.com-brand.png','/site-logos/ouyedisplay.com-icon.png'].includes(path))return context.next();
if(path==='/health')return json({ok:true,app:'Ouyee-Dashboard',version:'1.0.0'});
if(!env.DASHBOARD_PASSWORD||!env.SESSION_SECRET||!env.DASHBOARD_DATA)return new Response('看板正在配置，请稍后访问。',{status:503,headers:{'Cache-Control':'no-store'}});
if(request.method==='POST'){const origin=request.headers.get('Origin');if(origin&&origin!==url.origin)return json({error:'请求来源不匹配'},403)}
if(path==='/login'){if(request.method==='GET')return await session(request,env)?Response.redirect(url.origin+'/',303):login();if(request.method!=='POST')return json({error:'方法不支持'},405);const ip=request.headers.get('CF-Connecting-IP')||'local';const id=b64(await crypto.subtle.digest('SHA-256',enc.encode(ip))).slice(0,22);const limitKey='login:'+id,attempts=Number(await env.DASHBOARD_DATA.get(limitKey)||0);if(attempts>=10)return login('尝试次数过多，请 15 分钟后重试。',429);const form=await request.formData();const password=String(form.get('password')||'');if(password.length>256||!await equal(password,env.DASHBOARD_PASSWORD)){await env.DASHBOARD_DATA.put(limitKey,String(attempts+1),{expirationTtl:900});return login('密码不正确，请重新输入。',401)}await env.DASHBOARD_DATA.delete(limitKey);const p=b64(enc.encode(JSON.stringify({v:1,exp:Date.now()+43200000})));return new Response(null,{status:303,headers:{Location:'/', 'Set-Cookie':secureCookie(p+'.'+await hmac(env.SESSION_SECRET,p),request),'Cache-Control':'no-store'}})}
if(path==='/api/ga4/read'){if(request.method!=='POST'||!env.SCHEDULER_TOKEN||!await equal(request.headers.get('Authorization')||'','Bearer '+env.SCHEDULER_TOKEN))return json({error:'未经授权'},401);try{const d=await env.DASHBOARD_DATA.get('latest',{type:'json'});if(!d)return json({error:'网站清单未就绪'},503);return json(await collectGa4(env,d.sites.map(s=>({domain:s.domain,ga4:null}))))}catch(e){return json({error:e.message},500)}}
if(path==='/api/scheduled-refresh'){if(request.method!=='POST')return json({error:'方法不支持'},405);if(!env.SCHEDULER_TOKEN||!await equal(request.headers.get('Authorization')||'','Bearer '+env.SCHEDULER_TOKEN))return json({error:'未经授权'},401);try{const input=await body(request);return json(await refreshDashboard(env,input.trigger==='schedule-test'?'schedule-test':'scheduled'))}catch(e){return json({error:e.message},e.status||500)}}
if(!await session(request,env)){if(path.startsWith('/api/'))return json({error:'请先登录'},401);return Response.redirect(url.origin+'/login',303)}
if(path==='/logout'&&request.method==='POST')return new Response(null,{status:303,headers:{Location:'/login','Set-Cookie':secureCookie('',request,true),'Cache-Control':'no-store'}});
try{
if(path==='/api/dashboard'&&request.method==='GET'){const d=await env.DASHBOARD_DATA.get('latest',{type:'json'});if(!d)return json({error:'还未读取初始数据，请点击刷新。'},503);const leads=await leadStore(env,d.sites);return json({...d,leads,refreshSchedule:{enabled:!!env.SCHEDULER_TOKEN,time:'08:00',timeZone:'Asia/Shanghai',lastRun:await env.DASHBOARD_DATA.get('scheduled-refresh-status',{type:'json'})},errors:[...d.errors,...(leads.source?.error?[{source:'真实询盘',message:leads.source.error}]:[])]})}
if(path==='/api/refresh'&&request.method==='POST'){try{return json(await refreshDashboard(env,'manual'))}catch(e){return json({error:e.message},e.status||500)}}
if(path==='/api/leads/sync'&&request.method==='POST'){const d=await env.DASHBOARD_DATA.get('latest',{type:'json'});if(!d)return json({error:'请先读取网站清单'},503);const leads=await leadStore(env,d.sites,true);if(leads.source?.error)return json({error:leads.source.error},502);return json({ok:true,count:leads.rows.length,updatedAt:leads.updatedAt})}
if(['/api/leads/preview','/api/leads/import'].includes(path)&&request.method==='POST'){const input=await body(request);if(typeof input.csv!=='string')return json({error:'请上传 CSV 内容'},400);const current=await leadStore(env),d=await env.DASHBOARD_DATA.get('latest',{type:'json'});if(!d)return json({error:'请先读取网站清单'},503);const p=validateLeads(input.csv,d.sites,current);if(path.endsWith('/preview'))return json(p);if(p.errors.length)return json({error:p.errors.slice(0,5).join('；')},400);if(input.expectedVersion!==(current.updatedAt||''))return json({error:'询盘数据已更新，请重新预览后导入'},409);if(!p.rows.length)return json({error:'没有新增登记，请检查重复编号'},400);const out={connected:true,updatedAt:new Date().toISOString(),rows:[...current.rows,...p.rows].sort((a,b)=>b.date.localeCompare(a.date))};await env.DASHBOARD_DATA.put('leads',JSON.stringify(out));return json({added:p.rows.length,duplicates:p.duplicateCount})}
if(path.startsWith('/api/'))return json({error:'接口不存在'},404);
const response=await context.next();const headers=new Headers(response.headers);headers.set('X-Content-Type-Options','nosniff');headers.set('X-Frame-Options','DENY');headers.set('Cache-Control','private, no-store');headers.set('Referrer-Policy','strict-origin-when-cross-origin');headers.set('Content-Security-Policy',"default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; font-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");return new Response(response.body,{status:response.status,headers})
}catch(e){console.error('Dashboard request:',e.message);return json({error:e.message||'读取暂时失败，请稍后重试'},500)}
}
