import {googleClient} from './google.js';
export const LEADS_SHEET_ID='1YQIJ7jHgiJi0YtXJKMSYhuqhbILwmN38KfTpvTWmW90';
export const SYNC_INTERVAL=300000;
const TAB_DOMAINS={'欧野1':'ouyedisplay.com','欧野2':'oydisplay.com','贝森':'bensonfixtures.com','观筑':'focusstoredisplay.com','谷雨烟店':'ouyeedispensary.com','小渔夫':'ouyeestoredisplay.com','candyfixtures.com':'candyfixtures.com','focuscarddisplay.com':'focuscarddisplay.com'};
const clean=v=>String(v??'').trim();
export function sourceDate(value){const s=clean(value).replace(/[年月./]/g,'-').replace(/日/g,'').replace(/-+/g,'-').split(/[T\s]/)[0],m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(!m)return '';const iso=`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;const d=new Date(iso+'T00:00:00Z');return !Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===iso?iso:''}
function host(value){try{const u=new URL(value.includes('://')?value:'https://'+value);return ['http:','https:'].includes(u.protocol)&&u.hostname.includes('.')?u.hostname.toLowerCase().replace(/^www\./,''):''}catch{return ''}}
export function sourceChannel(value){const s=clean(value),upper=s.toUpperCase();if(['SEM','GOOGLE ADS','GOOGLE ADWORDS','谷歌广告','GOOGLE广告'].includes(upper))return'Google Ads';if(['SEO','自然','自然搜索','自然流量','GOOGLE AI OVERVIEW','AI OVERVIEW','AIO'].includes(upper))return'自然搜索';if(upper==='GPT ADS'||upper==='GPT广告')return'GPT Ads';if(['CHATGPT','GPT','AI','AI推荐','AI 推荐','GPT推荐'].includes(upper))return'AI 推荐';if(['IG','INSTAGRAM'].includes(upper))return'Instagram';if(['FB','FACEBOOK'].includes(upper))return'Facebook';if(['邮箱直询','邮件直询'].includes(s))return'邮箱直询';if(['广告','推广'].includes(s))return'广告（平台未注明）';return'未知'}
function excelCol(n){let c='';while(n){const r=(n-1)%26;c=String.fromCharCode(65+r)+c;n=Math.floor((n-1)/26)}return c}
export function sourceHeader(values){return values.slice(0,8).findIndex(row=>row.some(x=>['日期','登记日期','询盘日期'].includes(clean(x)))&&row.some(x=>['姓名','客户名称','客户姓名','邮箱','WhatsApp'].includes(clean(x))))}
export function normalizeSheetTables(tables,sites,now=new Date(),whatsappDomain=''){
const rows=[],issues=[],tabs=[],seenIds=new Set(),signatures=new Set(),domains=sites.map(s=>s.domain),today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);let blankRows=0,duplicateRows=0,invalidDateRows=0,undatedRows=0,futureRows=0,unmappedRows=0,rawRegistered=0,qualificationAvailable=false;
for(const tab of tables){const headerAt=sourceHeader(tab.values);if(headerAt<0)continue;const header=tab.values[headerAt].map(clean);const index=(...names)=>header.findIndex(x=>names.includes(x));const get=(row,...names)=>{const i=index(...names);return i<0?'':clean(row[i])};const statusIndex=index('询盘状态','有效状态','是否有效','状态');if(statusIndex>=0)qualificationAvailable=true;let included=0,duplicates=0,skipped=0;const expected=TAB_DOMAINS[tab.title]||((tab.title==='欧野-whatsapp')?whatsappDomain:domains.includes(tab.title)?tab.title:'');
for(let i=headerAt+1;i<tab.values.length;i++){const row=tab.values[i],dateRaw=get(row,'日期','登记日期','询盘日期'),name=get(row,'客户名称','姓名','客户姓名'),email=get(row,'邮箱','邮件','Email'),phone=get(row,'电话','WhatsApp','手机','Phone'),category=get(row,'店铺','类目','产品'),message=get(row,'信息','客户留言','询盘内容');const isContact=!!(name||email||phone);if(!isContact&&!(dateRaw&&(category||message))){blankRows++;skipped++;continue}rawRegistered++;const date=sourceDate(dateRaw);if(!date){if(dateRaw)invalidDateRows++;else undatedRows++;issues.push({tab:tab.title,row:i+1,type:dateRaw?'日期格式待核对':'未填写日期'})}if(date&&date>today){futureRows++;issues.push({tab:tab.title,row:i+1,type:'未来日期，未计入当前周期'})}
const explicitUrl=get(row,'询盘来源URL','来源网址','网站','网站域名'),projectNotes=get(row,'客户具体项目信息和跟进情况');const noteHosts=[...new Set((projectNotes.match(/https?:\/\/[^\s<>"'，。；）)]+/gi)||[]).map(host).filter(h=>domains.some(d=>h===d||h.endsWith('.'+d))))];const noteDomains=[...new Set(noteHosts.map(h=>domains.find(d=>h===d||h.endsWith('.'+d))))];const noteUrl=noteDomains.length===1?(projectNotes.match(/https?:\/\/[^\s<>"'，。；）)]+/gi)||[]).find(u=>domains.some(d=>host(u)===d||host(u).endsWith('.'+d)))||'':'';const url=explicitUrl||noteUrl,urlHost=host(url);let domain='',domainBasis='未注明来源网站';if(urlHost){domain=domains.find(d=>d===urlHost)||domains.find(d=>urlHost.endsWith('.'+d))||'';domainBasis=domain?'来源网址':'来源域名未在网站清单';}else if(expected&&domains.includes(expected)){domain=expected;domainBasis='工作表对应网站';}if(!domain)unmappedRows++;
const group=sites.find(s=>s.domain===domain)?.group||(tab.title.startsWith('欧野')||tab.title==='谷雨烟店'||tab.title==='小渔夫'?'欧野':tab.title==='观筑'?'观筑':tab.title==='贝森'?'贝森':'其他'),rawChannel=get(row,'渠道','来源渠道','询盘渠道')||(tab.title==='欧野-whatsapp'&&!header[0]?clean(row[0]):'');let status='未标注';const rawStatus=statusIndex<0?'':clean(row[statusIndex]);if(['有效','是','有效询盘'].includes(rawStatus))status='有效';else if(['垃圾','无效','否','垃圾询盘'].includes(rawStatus))status='垃圾';else if(['待确认','待审核','待核实'].includes(rawStatus))status='待确认';const mail=get(row,'Gmail邮件ID','邮件ID');const signature=JSON.stringify([dateRaw,name,email,phone,category,message,rawChannel,url,get(row,'客户具体项目信息和跟进情况'),get(row,'是否成交')]);const id=mail?'gmail:'+mail:`sheet:${tab.sheetId}:${i+1}`;if(seenIds.has(id)||signatures.has(tab.sheetId+':'+signature)){duplicateRows++;duplicates++;continue}seenIds.add(id);signatures.add(tab.sheetId+':'+signature);
rows.push({id,date,domain,group,domainBasis,channel:sourceChannel(rawChannel),rawChannel,status,country:get(row,'国家','国家/城市','国家/地区'),company:get(row,'公司','公司名称'),contact:name||email||phone,email,phone,category,owner:get(row,'跟进人','跟进业务员','跟进业务','跟进','业务员'),notes:[message,get(row,'客户具体项目信息和跟进情况')].filter(Boolean).join('\n').slice(0,2000),contactMethod:tab.title==='欧野-whatsapp'?'WhatsApp':'网站 / 邮件',dealStatus:get(row,'是否成交'),sourceUrl:url,sourceTab:tab.title,sourceSheetId:tab.sheetId,sourceRow:i+1,dateRaw});included++}
tabs.push({title:tab.title,id:tab.sheetId,registered:included,duplicates,skipped,domain:expected||null})}
rows.sort((a,b)=>b.date.localeCompare(a.date)||b.sourceRow-a.sourceRow);const dated=rows.filter(r=>r.date&&r.date<=today).map(r=>r.date).sort();return{connected:true,updatedAt:now.toISOString(),rows,qualificationAvailable,source:{type:'google_sheet',id:LEADS_SHEET_ID,title:'官网询盘统计表',gid:562092960,syncedAt:now.toISOString(),intervalMinutes:5,mode:'replace_from_sheet',rawRegistered,registered:rows.length,duplicateRows,blankRows,invalidDateRows,undatedRows,futureRows,unmappedRows,dateMin:dated[0]||null,dateMax:dated.at(-1)||null,tabs,issues,whatsappDomain:whatsappDomain||null}}
}
export async function collectLeadsSheet(env,sites,client){const api=client||await googleClient(env),base=`https://sheets.googleapis.com/v4/spreadsheets/${LEADS_SHEET_ID}`;const meta=await api(base+'?fields=properties(title),sheets(properties(sheetId,title,gridProperties))');const sheets=meta.sheets.map(x=>x.properties).filter(x=>x.gridProperties&&x.title!=='国家区号'&&!['业务员统计','询盘品类占比','询盘国家占比'].includes(x.title));const headerRanges=sheets.map(s=>`'${s.title.replaceAll("'","''")}'!A1:${excelCol(Math.min(s.gridProperties.columnCount,32))}8`);const headers=await api(base+'/values:batchGet?'+new URLSearchParams([...headerRanges.map(x=>['ranges',x]),['valueRenderOption','FORMATTED_VALUE']]));const selected=[];headers.valueRanges.forEach((r,i)=>{const h=sourceHeader(r.values||[]);if(h>=0)selected.push({...sheets[i],width:r.values[h].length})});if(!selected.length)throw new Error('询盘表中没有识别到登记工作表');const tables=[];
for(let i=0;i<selected.length;i+=10){const part=selected.slice(i,i+10);const ranges=[];for(const s of part){const chunkRows=Math.max(1,Math.floor(48000/s.width));for(let start=1;start<=s.gridProperties.rowCount;start+=chunkRows)ranges.push({sheet:s,range:`'${s.title.replaceAll("'","''")}'!A${start}:${excelCol(s.width)}${Math.min(s.gridProperties.rowCount,start+chunkRows-1)}`,start})}const data=await api(base+'/values:batchGet?'+new URLSearchParams([...ranges.map(x=>['ranges',x.range]),['valueRenderOption','FORMATTED_VALUE']]));for(let j=0;j<ranges.length;j++){const s=ranges[j].sheet;let table=tables.find(t=>t.sheetId===s.sheetId);if(!table){table={sheetId:s.sheetId,title:s.title,values:[]};tables.push(table)}const vals=data.valueRanges[j].values||[];while(table.values.length<ranges[j].start-1)table.values.push([]);table.values.push(...vals)}}
const out=normalizeSheetTables(tables,sites,new Date(),env.LEADS_WHATSAPP_DOMAIN||'');out.source.title=meta.properties.title;return out}
export async function syncLeadsSheet(env,sites,force=false,client){const old=await env.DASHBOARD_DATA.get('sheet-leads',{type:'json'}),status=force?null:await env.DASHBOARD_DATA.get('sheet-sync-status',{type:'json'});const checked=status?.attemptedAt||old?.updatedAt;if(!force&&checked&&Date.now()-Date.parse(checked)<SYNC_INTERVAL)return old?{...old,source:{...old.source,error:status?.error||null}}:{connected:false,rows:[],source:{id:LEADS_SHEET_ID,title:'官网询盘统计表',gid:562092960,error:status?.error||null}};
try{const data=await collectLeadsSheet(env,sites,client);await env.DASHBOARD_DATA.put('sheet-leads',JSON.stringify(data));await env.DASHBOARD_DATA.put('sheet-sync-status',JSON.stringify({attemptedAt:data.updatedAt,error:null}));return data}catch(e){await env.DASHBOARD_DATA.put('sheet-sync-status',JSON.stringify({attemptedAt:new Date().toISOString(),error:e.message}));return old?{...old,source:{...old.source,error:e.message}}:{connected:false,rows:[],source:{id:LEADS_SHEET_ID,title:'官网询盘统计表',gid:562092960,error:e.message}}}}
