import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
import {isSocialAd} from '../cloud/ad-scope.js';import {normalizeSheetTables,sourceChannel} from '../cloud/sheet-leads.js';
const code=ts.transpileModule(fs.readFileSync(new URL('../src/data.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace('../cloud/ad-scope.js',new URL('../cloud/ad-scope.js',import.meta.url).href);
const {adRows,sumAds,inquiryAcquisition,inquiryAcquisitionSummary,getSiteGsc,percentOf,platformInquiryCounts}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const sites=[{domain:'oydisplay.com',group:'欧野'},{domain:'ouyedisplay.com',group:'欧野'}];
const row=(id,channel='DEMAND_GEN',campaign='Campaign')=>({campaignId:id,channel,campaign,domain:'oydisplay.com',date:'2026-10-06',costMicros:1000000,clicks:1,impressions:10,conversions:1});
const d={sites,accounts:[{id:'a',currency:'CNY',name:'A',daily:[row('23863935806'),row('search','SEARCH')]},{id:'b',currency:'CNY',name:'B',daily:[row('23871949843'),row('other-demand')]}]},period={start:'2026-10-01',end:'2026-10-06'};
assert.equal(sumAds(adRows(d,sites,period)).cost,2);assert.equal(sumAds(adRows(d,sites,period,'social')).cost,2);assert.equal(sumAds(adRows(d,sites,period,'all')).cost,4);assert.equal(isSocialAd(row('other-demand')),false);assert.equal(isSocialAd(row('new','VIDEO')),true);assert.equal(isSocialAd(row('new','DEMAND_GEN','YouTube new')),true);assert.equal(adRows(d,[sites[1]],period).length,0);
const headers=['','日期','姓名','国家','WhatsApp','类目','客户留言','跟进','客户具体项目信息和跟进情况'];
const urls=['https://oydisplay.com/','项目 https://www.ouyedisplay.com/contact/','https://oydisplay.com/','https://oydisplay.com/ https://ouyedisplay.com/','https://oydisplay.com.attacker.test/'];
const t={sheetId:562092960,title:'欧野-whatsapp',values:[headers,...urls.map((u,i)=>[['SEO','Google Ads','GPT','SEO','SEO'][i],'2026年10月6日','','US',String(i),'','','',u])]};
const leads=normalizeSheetTables([t],sites,new Date('2026-10-09T00:00:00Z')).rows;const lead=i=>leads.find(r=>r.phone===String(i));assert.equal(lead(0).domain,'oydisplay.com');assert.equal(lead(0).channel,'自然搜索');assert.equal(lead(1).domain,'ouyedisplay.com');assert.equal(inquiryAcquisition(lead(1)),'广告询盘');assert.equal(lead(2).channel,'AI 推荐');assert.equal(lead(3).domain,'');assert.equal(lead(4).domain,'');assert.equal(sourceChannel('AI Overview'),'自然搜索');assert.equal(sourceChannel('自然'),'自然搜索');assert.equal(inquiryAcquisition({channel:'未知'}),'来源未标注');
console.log('PASS: both social campaigns, spend/site scopes, WhatsApp URL/blank-header source, ambiguous domains and inquiry split');

const summary=inquiryAcquisitionSummary([{channel:'Google Ads'},{channel:'自然搜索'},{channel:'AI 推荐'},{channel:'未知'}]);assert.deepEqual(summary,{total:4,paid:1,natural:2,unmarked:1,paidShare:25,naturalShare:50});assert.equal(inquiryAcquisitionSummary([]).paidShare,null);console.log('PASS: unmarked historical sources stay separate, shares use all inquiries, empty denominator guarded');

assert.equal(sourceChannel('GPT ads'),'GPT Ads');assert.equal(sourceChannel('GPT'),'AI 推荐');assert.equal(inquiryAcquisition({channel:'GPT Ads'}),'广告询盘');assert.equal(inquiryAcquisitionSummary([{channel:'GPT Ads'},{channel:'Google Ads'},{channel:'AI 推荐'}]).paid,2);console.log('PASS: GPT Ads is paid, GPT recommendation is organic');

assert.equal(getSiteGsc({gsc:{availableEnd:'2026-10-06',daily:[]}}, {start:'2026-10-09',end:'2026-10-09'}),null);console.log('PASS: unavailable GSC date returns no value, not zero');

const searchData={...d,gptAds:{accountName:'GPT',currency:'CNY',daily:[row('gpt','GPT_ADS')]},accounts:[...d.accounts,{id:'c',currency:'CNY',name:'C',daily:[row('video','VIDEO'),row('display','DISPLAY'),row('pmax','PERFORMANCE_MAX'),row('youtube-search','SEARCH','YouTube promotion'),row('23863935806','SEARCH')]}]};assert.equal(sumAds(adRows(searchData,sites,period,'search')).cost,1);assert.equal(adRows(searchData,[sites[1]],period,'search').length,0);assert.equal(adRows(searchData,sites,{start:'2026-10-07',end:'2026-10-09'},'search').length,0);console.log('PASS: search spend excludes video, social campaign IDs, Demand Gen, display, PMax and GPT; site/date filters preserved');

assert.deepEqual(platformInquiryCounts([{channel:'Google Ads'},{channel:'GPT Ads'},{channel:'广告（平台未注明）'},{channel:'自然搜索'},{channel:'未知'}]),{google:1,gpt:1,otherPaid:1});assert.equal(percentOf(1,5),20);assert.equal(percentOf(0,0),null);assert.equal(percentOf(0,5),0);console.log('PASS: platform inquiry split, unknown paid platform and percentage denominators');
