import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import {normalizeGptAds} from '../cloud/gpt-ads.js';
const sites=[{domain:'oydisplay.com',group:'欧野'},{domain:'ouyedisplay.com',group:'欧野'}];
const input={currency:'CNY',domain:'oydisplay.com',sourceFile:'test.xlsx',accountName:'Test',expectedTotal:10,rows:[{date:'2026-10-01',campaign:'A',cost:6,clicks:3,impressions:10,conversions:1},{date:'2026-10-04',campaign:'A',cost:4,clicks:2,impressions:8,conversions:0}]};
const store=normalizeGptAds(input,sites,new Date('2026-10-09T00:00:00Z'));assert.equal(store.total,10);assert.equal(store.daily.length,2);assert.equal(store.end,'2026-10-04');assert.throws(()=>normalizeGptAds({...input,currency:'?'},sites));assert.throws(()=>normalizeGptAds({...input,expectedTotal:11},sites));assert.throws(()=>normalizeGptAds({...input,rows:[input.rows[0],input.rows[0]]},sites));assert.throws(()=>normalizeGptAds({...input,domain:'unknown.test'},sites));assert.throws(()=>normalizeGptAds({...input,rows:[{...input.rows[0],cost:-1}]},sites));
const code=ts.transpileModule(fs.readFileSync(new URL('../src/data.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace('../cloud/ad-scope.js',new URL('../cloud/ad-scope.js',import.meta.url).href);const {adRows,sumAds,gptSpendCovered}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const d={sites,accounts:[],gptAds:store,leads:{rows:[{date:'2026-10-02',channel:'GPT Ads',domain:'oydisplay.com'}]}};const p={start:'2026-10-01',end:'2026-10-04'};assert.equal(sumAds(adRows(d,sites,p)).cost,10);assert.equal(adRows(d,[sites[1]],p).length,0);assert.equal(gptSpendCovered(d,sites,p),true);assert.equal(gptSpendCovered(d,sites,{...p,end:'2026-10-09'}),false);assert.equal(gptSpendCovered({...d,leads:{rows:[]}},sites,{...p,end:'2026-10-09'}),false);assert.equal(adRows(d,sites,p,'social').length,0);
console.log('PASS: manual import validates totals/dates/currency/domain, combines daily spend, filters sites, and blocks costs beyond exported coverage');

const converted=normalizeGptAds({...input,currency:'USD',targetCurrency:'CNY',exchangeRate:7},sites);assert.equal(converted.total,70);assert.equal(converted.sourceTotal,10);assert.equal(converted.currency,'CNY');assert.equal(converted.daily[0].sourceCostMicros,6000000);assert.equal(converted.daily[0].costMicros,42000000);assert.throws(()=>normalizeGptAds({...input,currency:'USD',targetCurrency:'CNY'},sites));console.log('PASS: original USD reconciliation and fixed 7 CNY conversion preserved');

assert.equal(gptSpendCovered({...d,leads:{rows:[{date:'2026-10-02',channel:'GPT Ads',domain:'ouyedisplay.com'}]}},sites,p),true,'report covers the company account even if an inquiry names another company website');const focus={domain:'focus.test',group:'观筑'};assert.equal(gptSpendCovered({...d,sites:[...sites,focus],leads:{rows:[{date:'2026-10-02',channel:'GPT Ads',domain:focus.domain}]}},[...sites,focus],p),false,'another company account is not covered');
