import {useState} from 'react';
import {Megaphone,MousePointer2,Eye,ClipboardCheck,Info} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip} from 'recharts';
import type {Dashboard,Period,Site} from '../types';
import {adRows,groupCampaigns,sumAds,number,money,days} from '../data';
import {Metric,Panel,Empty} from './ui';
import {CampaignBars} from './Charts';
type Platform='Google Ads'|'GPT Ads';
function PlatformAds({platform,data,sites,period,view}:{platform:Platform;data:Dashboard;sites:Site[];period:Period;view:'summary'|'details'}){
 const [metric,setMetric]=useState<'cost'|'clicks'|'impressions'>('cost');
 const gpt=platform==='GPT Ads',source=data.gptAds,rows=adRows(data,sites,period).filter(r=>(r.accountId==='gpt-manual')===gpt),campaigns=groupCampaigns(rows),total=sumAds(rows),currencies=[...new Set(rows.map(r=>r.currency))],mixed=currencies.length>1,currency=currencies[0]||(gpt?source?.currency:data.accounts[0]?.currency)||'CNY';
 const start=gpt?source?.start:data.period.previousStart,end=gpt?source?.end:data.period.end,connected=gpt?!!source:data.accounts.length>0,matched=!gpt||!!source&&sites.some(s=>s.domain===source.domain),overlap=!!start&&!!end&&period.start<=end&&period.end>=start,available=connected&&matched&&overlap,partial=available&&!!start&&!!end&&(period.start<start||period.end>end);
 const daily=days(period).map(date=>{const known=available&&date>=start!&&date<=end!;const r=sumAds(rows.filter(x=>x.date===date));return {date:date.slice(5).replace('-','.'),value:known?r[metric]:null}});
 const accountLabel=gpt?'OUYEE':`${data.accounts.length} 个账户`;
 return <section className="platform-ads" aria-label={`${platform} ${view==='summary'?'广告数据':'广告明细'}`}><div className="core-heading"><h2>{platform}{view==='details'?' · 趋势与明细':''}</h2><span className="muted">{gpt?'导入报表':accountLabel} · {start||'—'} — {end||'—'}</span></div>
 {view==='summary'&&<><div className="metrics-grid"><Metric label="广告花费" value={mixed?'多币种，未合并':money(available?total.cost:null,currency)} foot={partial?'所选周期已读取部分':'所选周期累计花费'} icon={<Megaphone size={19}/>}/><Metric label="广告点击" value={number(available?total.clicks:null)} foot="所选周期累计点击" icon={<MousePointer2 size={19}/>}/><Metric label="广告展示" value={number(available?total.impressions:null)} foot="所选周期累计展示" icon={<Eye size={19}/>}/><Metric label="平台转化" value={number(available?total.conversions:null,2)} foot="平台事件，与登记询盘分开统计" icon={<ClipboardCheck size={19}/>}/></div>
 {partial&&<div className="notice"><Info size={17}/><span>{platform} 数据仅覆盖 {start} 至 {end}，当前周期显示已读取部分，覆盖日期外的数据未按零处理。</span></div>}
 {gpt&&source&&<div className="ad-source-caption">推广网站：{source.domain} · 原币 {source.sourceCurrency||source.currency}{source.exchangeRate&&source.exchangeRate!==1?` · 固定汇率 ${source.exchangeRate}`:''} · 更新于 {new Date(source.importedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}</div>}
 </>}{view==='details'&&(available?<><div className="chart-grid"><Panel title="每日广告趋势" sub={`${period.start} — ${period.end}`} action={<div className="segmented" aria-label={`${platform} 趋势指标`}>{(['cost','clicks','impressions'] as const).map(k=><button key={k} className={metric===k?'selected':''} onClick={()=>setMetric(k)}>{k==='cost'?'花费':k==='clicks'?'点击':'展示'}</button>)}</div>}><div className="chart-wrap">{mixed&&metric==='cost'?<div className="chart-empty">多个币种暂不合并绘图</div>:<ResponsiveContainer width="100%" height="100%"><LineChart data={daily} margin={{top:15,right:14,left:0,bottom:4}}><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="date" axisLine={false} tickLine={false} minTickGap={38} tick={{fill:'var(--chart-label)',fontSize:12}}/><YAxis width={54} axisLine={false} tickLine={false} tick={{fill:'var(--chart-label)',fontSize:12}} tickFormatter={v=>number(v)}/><Tooltip contentStyle={{background:'var(--surface)',color:'var(--chart-text)',border:'1px solid var(--border)',borderRadius:10}} formatter={v=>[metric==='cost'?money(Number(v),currency):number(Number(v)),metric==='cost'?'花费':metric==='clicks'?'点击':'展示']}/><Line type="monotone" dataKey="value" stroke="var(--chart-accent)" strokeWidth={2.5} dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer>}</div></Panel><Panel title="广告系列花费" sub="所选周期 · 按花费排序">{mixed?<div className="chart-empty">多个币种暂不合并绘图</div>:<CampaignBars rows={campaigns}/>}</Panel></div>
 <Panel title="广告系列明细" sub={`${campaigns.length} 个有投放数据的广告系列`}><div className="table-scroll"><table><thead><tr><th>广告系列</th><th>目标网站</th><th>花费</th><th>点击</th><th>展示</th><th>平台转化</th></tr></thead><tbody>{campaigns.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small className="table-sub">{c.accountName}</small></td><td>{c.domain||'未匹配网站'}</td><td>{money(c.cost,c.currency)}</td><td>{number(c.clicks)}</td><td>{number(c.impressions)}</td><td>{number(c.conversions,2)}</td></tr>)}</tbody></table>{!campaigns.length&&<div className="table-empty">当前周期没有投放记录</div>}</div></Panel></>:<Panel title="广告数据"><Empty title={!connected?`${platform} 数据尚未接入`:!matched?'所选网站没有对应投放':'所选日期尚无报表数据'} description="可切换网站或日期查看已有报表。" icon={<Megaphone size={28}/>}/></Panel>)}
 </section>
}
export function AdsPage(props:{data:Dashboard;sites:Site[];period:Period}){return <><div className="notice"><Info size={17}/><span>Google Ads 与 GPT Ads 按相同指标分别展示，平台转化与真实登记询盘分开统计。</span></div><div className="ad-platform-summaries" aria-label="广告平台数据对比"><PlatformAds platform="Google Ads" view="summary" {...props}/><PlatformAds platform="GPT Ads" view="summary" {...props}/></div><PlatformAds platform="Google Ads" view="details" {...props}/><PlatformAds platform="GPT Ads" view="details" {...props}/></>}
