import {useId} from 'react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,BarChart,Bar} from 'recharts';
import type {ReactNode} from 'react';
import {Panel,Status} from './ui';
import {number,money,days,getSiteGsc,adRows} from '../data';
import type {Dashboard,Period,Site} from '../types';
export function TrendChart({data,sites,period,metric,setMetric}:{data:Dashboard;sites:Site[];period:Period;metric:'clicks'|'impressions'|'cost';setMetric:(v:'clicks'|'impressions'|'cost')=>void}){const gradient=useId().replaceAll(':','');const ads=adRows(data,sites,period),gscEnd=data.period.gscEnd||data.period.end,currencies=[...new Set(ads.map(r=>r.currency))];const chart=days(period).map(date=>({date:date.slice(5).replace('-','.'),value:metric!=='cost'&&date>gscEnd?null:metric==='cost'?ads.filter(r=>r.date===date).reduce((n,r)=>n+r.costMicros,0)/1e6:sites.reduce((n,s)=>n+(s.gsc?.daily.find(d=>d.date===date)?.[metric]||0),0)}));const connected=metric==='cost'?ads.length>0&&currencies.length<=1:sites.some(s=>s.gsc)&&period.start<=gscEnd;return <Panel title={metric==='cost'?'广告花费趋势':'自然搜索趋势'} sub={`${period.start} — ${period.end}${metric!=='cost'&&period.end>gscEnd?' · 搜索数据截至 '+gscEnd:''}`} action={<div className="segmented" aria-label="趋势指标">{(['clicks','impressions','cost'] as const).map(k=><button key={k} className={metric===k?'selected':''} onClick={()=>setMetric(k)}>{k==='clicks'?'点击':k==='impressions'?'展示':'花费'}</button>)}</div>} className="trend-panel"><div className="chart-wrap">{connected?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:15,right:14,left:0,bottom:4}}><defs><linearGradient id={gradient} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-accent)" stopOpacity={0.2}/><stop offset="100%" stopColor="var(--chart-accent)" stopOpacity={0.01}/></linearGradient></defs><CartesianGrid stroke="var(--chart-grid)" vertical={false}/><XAxis dataKey="date" axisLine={false} tickLine={false} minTickGap={38} tick={{fill:'var(--chart-label)',fontSize:12}} dy={9}/><YAxis axisLine={false} tickLine={false} width={54} tick={{fill:'var(--chart-label)',fontSize:12}} tickFormatter={v=>number(v)} /><Tooltip contentStyle={{background:'var(--surface)',color:'var(--chart-text)',border:'1px solid var(--border)' ,borderRadius:10,fontSize:13,boxShadow:'0 8px 24px #1018280a'}} formatter={(v)=>[metric==='cost'?money(Number(v),currencies[0]):number(Number(v)),metric==='clicks'?'搜索点击':metric==='impressions'?'搜索展示':'广告花费']} labelStyle={{color:'var(--chart-text)'}} cursor={{stroke:'var(--chart-grid)'}} labelFormatter={l=>l+' · 每日数据'}/><Area isAnimationActive={false} type="monotone" dataKey="value" stroke="var(--chart-accent)" strokeWidth={2.5} fill={`url(#${gradient})`} activeDot={{r:5,stroke:'#fff',strokeWidth:2}}/></AreaChart></ResponsiveContainer>:<div className="chart-empty">{currencies.length>1&&metric==='cost'?'多币种花费暂不合并绘图':metric!=='cost'&&period.start>gscEnd?'所选日期的搜索数据尚未返回':'所选网站的数据尚未接入'}</div>}</div></Panel>}
export function ConnectionPanel({data,onOpen}:{data:Dashboard;onOpen:()=>void}){const connected=data.sites.filter(s=>s.gsc).length,total=data.sites.length;return <Panel title="数据接入概况" action={<button className="text-button" onClick={onOpen}>查看</button>} className="connection-panel"><div className="ring" style={{background:`conic-gradient(var(--chart-accent) ${connected/total*360}deg,var(--ring-track) 0)`}}><div><strong>{connected}<span> / {total}</span></strong><small>网站搜索数据</small></div></div><div className="connection-list"><div><span><i className="dot blue"/>GSC</span><Status state="connected">{connected} 个网站</Status></div><div><span><i className="dot cyan"/>Google Ads</span><Status state={data.accounts.length?'connected':'pending'}>{data.accounts.length} 个账户</Status></div><div><span><i className="dot gray"/>GA4</span><Status state={data.sites.some(s=>s.ga4)?'connected':'pending'}>{data.sites.some(s=>s.ga4)?`${data.sites.filter(s=>s.ga4).length} 个网站`:'待授权'}</Status></div><div><span><i className="dot gray"/>真实询盘</span><Status state={data.leads.connected?'connected':'pending'}>{data.leads.connected?'已接入':'待接入'}</Status></div></div></Panel>}
export function CampaignBars({rows}:{rows:{name:string;cost:number}[]}){return <div className="bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows.slice(0,6)} layout="vertical" margin={{left:0,right:30,top:0,bottom:0}}><CartesianGrid stroke="var(--chart-grid)" horizontal={false}/><XAxis type="number" axisLine={false} tickLine={false} tick={{fill:'var(--chart-label)',fontSize:12}}/><YAxis type="category" dataKey="name" width={135} axisLine={false} tickLine={false} tick={{fill:'var(--chart-label)',fontSize:11}} tickFormatter={v=>v.length>18?v.slice(0,17)+'…':v}/><Tooltip labelStyle={{color:'var(--chart-text)'}} cursor={{fill:'var(--chart-grid)',opacity:0.4}} formatter={v=>[money(Number(v)),'广告花费']} contentStyle={{background:'var(--surface)',color:'var(--chart-text)',border:'1px solid var(--border)',borderRadius:10,fontSize:13}}/><Bar isAnimationActive={false} dataKey="cost" fill="var(--chart-accent)" radius={[0,4,4,0]} barSize={18}/></BarChart></ResponsiveContainer></div>}
export function KeyLine({label,value}:{label:string;value:ReactNode}){return <div className="key-line"><span>{label}</span><strong>{value}</strong></div>}
