import {useEffect,useState} from 'react';
import {Inbox,Download,Megaphone,MessageCircle,RefreshCw,ExternalLink,Info,Search,ChevronLeft,ChevronRight,Link2} from 'lucide-react';
import type {Dashboard,Site,Period} from '../types';
import {api,filterLeads,selectLeads,downloadCsv,number,money,adRows,sumAds,offsetDate,inquiryOpportunityCost,inquiryAcquisition} from '../data';
import {Panel,Metric,Button,Empty,Status} from './ui';
export function LeadsPage({data,sites,period,onUpdate,onMessage}:{data:Dashboard;sites:Site[];period:Period;onUpdate:()=>Promise<void>;onMessage:(s:string)=>void}){
 const [scope,setScope]=useState<'period'|'recent'|'all'>('period'),[search,setSearch]=useState(''),[status,setStatus]=useState('全部'),[channel,setChannel]=useState('全部'),[page,setPage]=useState(0),[busy,setBusy]=useState(false);
 const source=data.leads.source,today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),viewPeriod=scope==='recent'?{start:offsetDate(today,-27),end:today}:period;
 const rows=scope==='all'?selectLeads(data,sites).filter(r=>!r.date||r.date<=today):filterLeads(data,sites,viewPeriod),paid=rows.filter(r=>inquiryAcquisition(r)==='广告询盘').length,natural=rows.filter(r=>inquiryAcquisition(r)==='自然 / AI 推荐询盘').length,gpt=rows.filter(r=>r.channel==='GPT Ads').length,whatsapp=rows.filter(r=>r.contactMethod==='WhatsApp'||r.channel==='WhatsApp').length;
 const connected=data.leads.connected,ads=adRows(data,sites,viewPeriod),adCost=sumAds(ads).cost,currencies=new Set(ads.map(r=>r.currency)),completeAds=scope!=='all'&&viewPeriod.start>=data.period.previousStart&&viewPeriod.end<=data.period.end,cost=inquiryOpportunityCost(adCost,rows.length,connected&&ads.length>0&&currencies.size===1&&completeAds);
 const channelNames=[...new Set(rows.map(r=>r.channel))].sort(),channelOptions=[...new Set(data.leads.rows.map(r=>r.channel))].sort(),visible=rows.filter(r=>(status==='全部'||r.status===status)&&(channel==='全部'||r.channel===channel||channel===inquiryAcquisition(r))&&[r.contact,r.company,r.email,r.phone,r.domain,r.country,r.owner,r.sourceTab].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase()));
 const pageSize=25,maxPage=Math.max(0,Math.ceil(visible.length/pageSize)-1),currentPage=Math.min(page,maxPage),channelCounts=channelNames.map(name=>({name,count:rows.filter(r=>r.channel===name).length})).sort((a,b)=>b.count-a.count),sourceNames=[...new Set(rows.map(r=>r.sourceTab||'手工登记'))],sourceCounts=sourceNames.map(name=>({name,count:rows.filter(r=>(r.sourceTab||'手工登记')===name).length})).sort((a,b)=>b.count-a.count);
 useEffect(()=>setPage(0),[scope,search,status,channel,period.start,period.end,sites.map(s=>s.domain).join(',')]);
 async function sync(){setBusy(true);try{const r=await api<{count:number}>('/api/leads/sync',{method:'POST',body:'{}'});await onUpdate();onMessage(`询盘表已同步，共 ${number(r.count)} 条登记记录`)}catch(e){onMessage('询盘同步未完成：'+(e as Error).message)}finally{setBusy(false)}}
 function exportRows(){downloadCsv('真实询盘登记.csv',[['询盘编号','登记日期','网站域名','询盘归类','获客来源','原始来源标注','有效状态','国家','客户名称','邮箱','电话','业务员','接收方式','来源工作表','原表行号'],...visible.map(r=>[r.id,r.date,r.domain,inquiryAcquisition(r),r.channel,r.rawChannel,r.status,r.country,r.contact,r.email,r.phone,r.owner,r.contactMethod,r.sourceTab,r.sourceRow])])}
 const scopeLabel=scope==='all'?'全部历史登记':`${viewPeriod.start} — ${viewPeriod.end}`;
 return <>
 <div className="metrics-grid"><Metric label="登记询盘" value={connected?number(rows.length):'—'} foot={scope==='all'?'全部历史登记，含未填日期记录':'所选日期内的登记记录'} icon={<Inbox size={19}/>}/><Metric label="广告带来的询盘" value={connected?number(paid):'—'} foot="SEM、Google Ads、GPT Ads 或广告" icon={<Megaphone size={19}/>}/><Metric label="自然 / AI 推荐询盘" value={connected?number(natural):'—'} foot="SEO、AI Overview、GPT 等非广告来源" icon={<MessageCircle size={19}/>}/><Metric label="单个询盘商机成本" value={money(cost,[...currencies][0])} foot={currencies.size>1?'币种不同，暂不合并计算':scope==='all'?'切换同周期查看单个询盘成本':!completeAds?'广告数据尚未覆盖完整登记周期':'已读取广告花费 ÷ 总询盘数'} icon={<Inbox size={19}/>}/></div>
 <Panel title="询盘登记表已连接" sub={source?.title||'登记数据'} action={<div className="action-group">{source&&<a className="button outline" href={`https://docs.google.com/spreadsheets/d/${source.id}/edit#gid=${source.gid}`} target="_blank" rel="noreferrer">打开原表<ExternalLink size={14}/></a>}<Button variant="primary" disabled={busy} onClick={()=>void sync()}><RefreshCw size={15} className={busy?'spin':''}/>{busy?'正在同步…':'同步询盘'}</Button></div>}>
 <div className="lead-source-details"><span><Link2 size={14}/>{source?.tabs?.length||0} 个登记工作表 · {number(data.leads.rows.length)} 条同步记录</span><span>同步于 {source?.syncedAt?new Date(source.syncedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—'}</span><span>当前周期 WhatsApp 登记 {number(whatsapp)} 条</span><span>打开看板自动检查；页面打开期间每 5 分钟检查更新。</span></div>
 {source?.error&&<div className="notice error-notice"><Info size={16}/><span>同步暂时失败，当前展示上次成功读取的数据：{source.error}</span></div>}
 <div className="notice lead-note"><Info size={16}/><span>{data.leads.qualificationAvailable?'有效状态按原表标记统计。':'原表未设置统一的有效状态列，目前统计真实登记数量，暂不评估有效客户数量。'}广告转化与登记询盘分别统计。2026 年 10 月起按登记来源区分广告与自然 / AI 推荐；之前来源登记不完整，历史占比和广告询盘成本仅供参考。未标注来源不计入自然询盘。</span></div>
 {source?.unmappedRows? <div className="lead-source-annotation">{number(source.unmappedRows)} 条历史登记未注明具体网站，保留在总览与对应公司组中；选择单个网站时不强行分配。{source.undatedRows?`另有 ${source.undatedRows} 条未填日期记录，可在“全部历史登记”查看。`:''}</div>:null}
 </Panel>
 <div className="lead-view-toolbar"><div className="segmented large">{([{key:'period',name:'与总览同周期'},{key:'recent',name:'最近 28 天 · 截至今天'},{key:'all',name:'全部历史登记'}] as const).map(v=><button key={v.key} className={scope===v.key?'selected':''} onClick={()=>setScope(v.key)}>{v.name}</button>)}</div><span className="muted">{scopeLabel}</span></div>
 <div className="lead-summary-grid"><Panel title="获客来源分布" sub={scopeLabel}><div className="lead-bars">{channelCounts.map(c=><button key={c.name} className="lead-bar" onClick={()=>{setChannel(c.name);setPage(0)}}><span>{c.name}</span><div><i style={{width:`${c.count/Math.max(1,channelCounts[0]?.count||1)*100}%`}}/></div><strong>{number(c.count)}</strong></button>)}{!rows.length&&<p className="muted">所选周期暂无登记</p>}</div></Panel><Panel title="工作表登记汇总" sub="按登记记录统计，不重复累计刷新结果"><div className="lead-tab-counts">{sourceCounts.map(t=><div key={t.name}><span>{t.name}</span><strong>{number(t.count)}</strong></div>)}{!rows.length&&<p className="muted">所选周期暂无登记</p>}</div></Panel></div>
 <Panel title="真实询盘登记" sub={`${scopeLabel} · 点击来源工作表可回到原始登记`} action={<Button onClick={exportRows} disabled={!connected}><Download size={15}/>导出登记</Button>}>
 {!connected?<Empty title="询盘数据尚未完成读取" description="请点击同步询盘，成功后会显示原表登记。" icon={<Inbox size={28}/>}/>:<>
 <div className="lead-table-filters"><label className="search-input"><Search size={15}/><input aria-label="搜索询盘" placeholder="搜索客户、网站、国家或业务员" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="筛选获客来源" value={channel} onChange={e=>setChannel(e.target.value)}><option value="全部">全部获客来源</option><option value="广告询盘">广告询盘 · 全部</option><option value="自然 / AI 推荐询盘">自然 / AI 推荐 · 全部</option>{channelOptions.map(s=><option key={s}>{s}</option>)}</select><select aria-label="筛选询盘状态" value={status} onChange={e=>setStatus(e.target.value)}>{['全部','未标注','有效','待确认','垃圾'].map(s=><option key={s} value={s}>{s==='全部'?'全部有效状态':s}</option>)}</select><span className="muted">{number(visible.length)} 条匹配登记</span></div>
 <div className="table-scroll"><table><thead><tr><th>登记日期</th><th>网站</th><th>询盘归类 / 来源</th><th>接收方式</th><th>客户 / 联系方式</th><th>国家</th><th>业务员</th><th>有效状态</th><th>原始登记</th></tr></thead><tbody>{visible.slice(currentPage*pageSize,(currentPage+1)*pageSize).map(r=><tr key={r.id}><td>{r.date||'未填日期'}</td><td>{r.domain||`${r.group||'未归属'} · 未注明网站`}</td><td>{inquiryAcquisition(r)}<small className="table-sub">{r.rawChannel||r.channel}</small></td><td>{r.contactMethod||'手工登记'}</td><td><strong>{r.contact||r.company||'未填客户名称'}</strong><small className="table-sub">{r.email||r.phone||''}</small></td><td>{r.country||'—'}</td><td>{r.owner||'—'}</td><td>{r.status==='未标注'?<span className="muted small">未标注</span>:<Status state={r.status==='有效'?'connected':r.status==='垃圾'?'error':'pending'}>{r.status}</Status>}</td><td>{r.sourceSheetId&&source?<a className="source-row-link" href={`https://docs.google.com/spreadsheets/d/${source.id}/edit#gid=${r.sourceSheetId}&range=A${r.sourceRow}:L${r.sourceRow}`} target="_blank" rel="noreferrer">{r.sourceTab}<small>第 {r.sourceRow} 行<ExternalLink size={10}/></small></a>:'手工登记'}</td></tr>)}</tbody></table>{!visible.length&&<div className="table-empty">没有匹配的登记记录</div>}</div>
 <div className="table-footer"><span>{visible.length?`${currentPage*pageSize+1}–${Math.min((currentPage+1)*pageSize,visible.length)} / ${number(visible.length)} 条`:'0 条登记'}</span><span>来源表新增、修改和删除后，下次同步会按最新内容重新汇总。</span><div className="pagination"><button aria-label="询盘上一页" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></button><span>{currentPage+1} / {maxPage+1}</span><button aria-label="询盘下一页" disabled={currentPage>=maxPage} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></button></div></div>
 </>}
 </Panel>
 </>
}
