import type {ReactNode,ButtonHTMLAttributes} from 'react';
import {CheckCircle2,Clock3,AlertCircle,ArrowUpRight,ArrowDownRight} from 'lucide-react';
// TailAdmin MIT: adapted primary/outline button family and light badge family.
export function Button({children,variant='outline',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'outline'|'ghost'}){return <button className={`button ${variant} ${className}`} {...props}>{children}</button>}
export function Status({state,children}:{state:'connected'|'pending'|'error';children:ReactNode}){const Icon=state==='connected'?CheckCircle2:state==='pending'?Clock3:AlertCircle;return <span className={`status ${state}`}><Icon size={13}/>{children}</span>}
export function Panel({title,sub,action,children,className=''}:{title:string;sub?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}><div className="panel-header"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>{children}</section>}
export function Delta({value,previous}:{value:number;previous:number}){if(!previous)return <span className="muted">上期暂无可比较数据</span>;const delta=(value-previous)/previous*100,up=delta>=0;return <span className={`delta ${up?'up':'down'}`}>{up?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {Math.abs(delta).toFixed(1)}% <span>较前一周期</span></span>}
export function Metric({label,value,foot,icon,delta}:{label:string;value:string;foot:ReactNode;icon:ReactNode;delta?:{value:number;previous:number}}){return <div className="metric"><div className="metric-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong><div className="metric-foot">{delta?<Delta {...delta}/>:foot}</div>{delta&&<div className="metric-source">{foot}</div>}</div>}
export function Empty({title,description,icon,action}:{title:string;description:string;icon:ReactNode;action?:ReactNode}){return <div className="empty"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{description}</p>{action}</div>}
