import {isSocialAd} from '../cloud/ad-scope.js';
import type {Dashboard,Site,Period,AdDay,Lead} from './types';
export const number=(value:number|null|undefined,digits=0)=>value==null?'—':new Intl.NumberFormat('zh-CN',{maximumFractionDigits:digits}).format(value);
export const money=(value:number|null|undefined,currency='CNY')=>value==null?'—':new Intl.NumberFormat('zh-CN',{style:'currency',currency,maximumFractionDigits:2}).format(value);
export const inside=(date:string,p:Period)=>date>=p.start&&date<=p.end;
export function offsetDate(date:string,days:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
export function days(p:Period){const rows:string[]=[];for(let d=p.start;d<=p.end;d=offsetDate(d,1))rows.push(d);return rows}
export function getSiteGsc(s:Site,p:Period){if(!s.gsc)return null;const r=s.gsc.daily.filter(x=>inside(x.date,p));const clicks=r.reduce((n,x)=>n+x.clicks,0),impressions=r.reduce((n,x)=>n+x.impressions,0);return{clicks,impressions,ctr:impressions?clicks/impressions:0,position:impressions?r.reduce((n,x)=>n+x.position*x.impressions,0)/impressions:null}}
export function adRows(d:Dashboard,sites:Site[],p:Period,scope:'website'|'social'|'all'='website'){const domains=new Set(sites.map(s=>s.domain));const all=sites.length===d.sites.length;return d.accounts.flatMap(a=>a.daily.filter(r=>inside(r.date,p)&&(scope==='all'||isSocialAd(r)===(scope==='social'))&&(all||!!r.domain&&domains.has(r.domain))).map(r=>({...r,currency:a.currency,accountId:a.id,accountName:a.name})))}
export function sumAds(rows:AdDay[]){return{cost:rows.reduce((n,r)=>n+r.costMicros,0)/1e6,clicks:rows.reduce((n,r)=>n+r.clicks,0),impressions:rows.reduce((n,r)=>n+r.impressions,0),conversions:rows.reduce((n,r)=>n+r.conversions,0)}}
export function leadSiteCovered(d:Dashboard,s:Site){if(!d.leads.connected)return false;if(d.leads.source?.type!=='google_sheet')return true;return !!d.leads.source.tabs?.some(t=>t.domain===s.domain)||d.leads.rows.some(r=>r.domain===s.domain)}
export function selectLeads(d:Dashboard,sites:Site[]){const domains=new Set(sites.map(s=>s.domain)),all=sites.length===d.sites.length,groups=new Set(sites.map(s=>s.group)),group=groups.size===1?[...groups][0]:null,wholeGroup=!!group&&sites.length===d.sites.filter(s=>s.group===group).length;return d.leads.rows.filter(r=>all||domains.has(r.domain)||!r.domain&&wholeGroup&&r.group===group)}
export function filterLeads(d:Dashboard,sites:Site[],p:Period){return selectLeads(d,sites).filter(r=>inside(r.date,p))}
export function downloadCsv(name:string,rows:(string|number|null|undefined)[][]){const safe=(v:string|number|null|undefined)=>{let s=String(v??'');if(/^[\s\u0000-\u001f]*[=+@-]/.test(s))s="'"+s;return'"'+s.replaceAll('"','""')+'"'};const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
export async function api<T>(url:string,options:RequestInit={}):Promise<T>{const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers}});if(r.status===401){location.assign('/login');throw new Error('请重新登录')}const a=await r.json();if(!r.ok)throw new Error(a.error||'请求失败，请稍后重试');return a}
export function groupCampaigns(rows:ReturnType<typeof adRows>){const map=new Map<string,{id:string;name:string;channel:string;currency:string;accountName:string;domain:string|null;clicks:number;impressions:number;cost:number;conversions:number}>();for(const r of rows){const key=r.accountId+':'+r.campaignId;const c=map.get(key)||{id:key,name:r.campaign,channel:r.channel,currency:r.currency,accountName:r.accountName,domain:r.domain,clicks:0,impressions:0,cost:0,conversions:0};c.clicks+=r.clicks;c.impressions+=r.impressions;c.cost+=r.costMicros/1e6;c.conversions+=r.conversions;map.set(key,c)}return [...map.values()].sort((a,b)=>b.cost-a.cost)}
export function leadCounts(rows:Lead[]){return{registered:rows.length,valid:rows.filter(r=>r.status==='有效').length,pending:rows.filter(r=>r.status==='待确认').length,spam:rows.filter(r=>r.status==='垃圾').length}}

export function inquiryOpportunityCost(spend:number,total:number,available:boolean){return available&&Number.isFinite(spend)&&spend>=0&&total>0?spend/total:null}

export function inquiryAcquisition(row:Lead){if(!row.channel||row.channel==='未知')return '来源未标注';return row.channel==='Google Ads'||row.channel==='广告（平台未注明）'?'广告询盘':'自然 / AI 推荐询盘'}

export function inquiryAcquisitionSummary(rows:Lead[]){const paid=rows.filter(r=>inquiryAcquisition(r)==='广告询盘').length,natural=rows.filter(r=>inquiryAcquisition(r)==='自然 / AI 推荐询盘').length;return {total:rows.length,paid,natural,unmarked:rows.length-paid-natural,paidShare:rows.length?paid/rows.length*100:null,naturalShare:rows.length?natural/rows.length*100:null}}
