import type {Lead,Period} from './types';
export type Breakdown={name:string;count:number;share:number};
export function datePreset(key:'30'|'previousMonth'|'thisMonth',end:string,today=end):Period{if(key==='30'){const d=new Date(end+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-29);return{start:d.toISOString().slice(0,10),end}}const month=today.slice(0,7);if(key==='thisMonth')return{start:month+'-01',end};const first=new Date(month+'-01T12:00:00Z');first.setUTCDate(0);const last=first.toISOString().slice(0,10);return{start:last.slice(0,7)+'-01',end:last<end?last:end}}
const blank=new Set(['','-','—','无','暂无','未知','未填写','未分配','不清楚','unknown','n/a','none']);
export function countryName(value:string){const s=value.trim(),key=s.toLowerCase();if(blank.has(key))return'未填写国家';const aliases:Record<string,string>={'usa':'美国','us':'美国','united states':'美国','united states of america':'美国','uk':'英国','united kingdom':'英国','great britain':'英国','uae':'阿联酋','united arab emirates':'阿联酋','阿拉伯联合酋长国':'阿联酋','沙特':'沙特阿拉伯','saudi arabia':'沙特阿拉伯','australia':'澳大利亚','canada':'加拿大','south africa':'南非','china':'中国','france':'法国','germany':'德国','india':'印度'};return aliases[key]||s}
export function ownerName(value:string){const s=value.trim();if(blank.has(s.toLowerCase())||s==='询盘不准确')return'未分配业务员';return s.replace(/\b[a-zA-Z]+\b/g,word=>word[0].toUpperCase()+word.slice(1).toLowerCase())}
export function categoryName(value:string){const s=value.trim(),key=s.toLowerCase();if(blank.has(key))return'未填写品类';const aliases:Record<string,string>={'咖啡':'咖啡 / 餐厅','咖啡店':'咖啡 / 餐厅','咖啡/餐厅':'咖啡 / 餐厅','咖啡/餐厅店':'咖啡 / 餐厅','餐厅':'咖啡 / 餐厅','coffee shop':'咖啡 / 餐厅','restaurant':'咖啡 / 餐厅','cafe':'咖啡 / 餐厅','kiosk':'Kiosk','商场展示亭':'Kiosk','mall kiosk':'Kiosk','珠宝':'珠宝店','化妆品':'化妆品店','香水':'香水店','眼镜':'眼镜店','服装':'服装店','手机':'手机店','假发':'假发店','冰淇淋':'冰淇淋店','shop design':'店铺设计','store design':'店铺设计'};return aliases[key]||s}
export function breakdown(rows:Lead[],field:'country'|'owner'|'category'):Breakdown[]{const clean=field==='country'?countryName:field==='owner'?ownerName:categoryName;const map=new Map<string,number>();for(const row of rows){const name=clean(row[field]||'');map.set(name,(map.get(name)||0)+1)}return [...map].map(([name,count])=>({name,count,share:rows.length?count/rows.length:0})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,'zh-CN'))}
export function topBreakdown(rows:Breakdown[],limit:number):Breakdown[]{if(rows.length<=limit)return rows;const missing=rows.find(r=>r.name==='未填写品类'),first=rows.slice(0,limit-1);if(missing&&!first.includes(missing)){first.pop();first.push(missing)}const kept=new Set(first.map(r=>r.name)),remaining=rows.filter(r=>!kept.has(r.name));return [...first,{name:'其余品类',count:remaining.reduce((n,r)=>n+r.count,0),share:remaining.reduce((n,r)=>n+r.share,0)}]}
export function monthlyTrend(rows:Lead[],end:string){const base=new Date(end.slice(0,7)+'-01T12:00:00Z');const months=Array.from({length:12},(_,i)=>{const d=new Date(base);d.setUTCMonth(d.getUTCMonth()-11+i);return{month:d.toISOString().slice(0,7),count:0}});const bins=new Map(months.map(m=>[m.month,m]));for(const row of rows){if(row.date&&row.date<=end){const bin=bins.get(row.date.slice(0,7));if(bin)bin.count++}}return months}
