export type Nav = 'overview' | 'sites' | 'ads' | 'leads' | 'connections';
export interface Day {date:string;clicks:number;impressions:number;ctr:number;position:number}
export interface Gsc {availableEnd?:string;clicks:number;impressions:number;ctr:number;position:number|null;previous:Omit<Gsc,'previous'|'daily'|'checkedAt'>;daily:Day[];checkedAt:string}
export interface Ga4 {property:string;sessions:number;activeUsers:number;engagedSessions:number;daily:{date:string;sessions:number;activeUsers:number;engagedSessions:number}[]}
export interface Site {name:string;domain:string;url:string;group:string;gsc:Gsc|null;gscProperty:string|null;gscError?:string;ga4:Ga4|null;ads:{accountId:string;currency:string;costMicros:number;clicks:number;conversions:number}|null;topPages?:{url:string;clicks:number;impressions:number;position:number}[]}
export interface AdDay {spendScope?:string;date:string;campaignId:string;campaign:string;channel:string;status:string;clicks:number;impressions:number;costMicros:number;conversions:number;domain:string|null}
export interface Account {id:string;name:string;currency:string;timeZone:string;daily:AdDay[];actions:{date:string;name:string;conversions:number;allConversions:number}[];unmappedCampaigns:string[];costMicros:number;clicks:number;impressions:number;conversions:number}
export interface Lead {id:string;date:string;domain:string;channel:string;status:string;country:string;company:string;contact:string;notes:string;email?:string;phone?:string;group?:string;domainBasis?:string;rawChannel?:string;category?:string;owner?:string;contactMethod?:string;dealStatus?:string;sourceUrl?:string;sourceTab?:string;sourceSheetId?:number;sourceRow?:number;dateRaw?:string}
export interface LeadSource {type?:string;id:string;title:string;gid:number;syncedAt?:string;intervalMinutes?:number;error?:string|null;registered?:number;duplicateRows?:number;undatedRows?:number;invalidDateRows?:number;futureRows?:number;unmappedRows?:number;dateMin?:string|null;dateMax?:string|null;tabs?:{title:string;id:number;registered:number;duplicates:number;skipped:number;domain:string|null}[];issues?:{tab:string;row:number;type:string}[]}
export interface LeadStore {connected:boolean;updatedAt?:string;rows:Lead[];qualificationAvailable?:boolean;source?:LeadSource}
export interface Dashboard {refreshSchedule?:{enabled:boolean;time:string;timeZone:string;lastRun?:{status:string;trigger?:string;startedAt?:string;finishedAt?:string;message?:string;coverage?:{gsc:number;ga4:number;ads:number;inquiries:number}}|null};checkedAt:string;period:{start:string;end:string;gscEnd?:string;previousStart:string;days:number;timeZone:string};sheet:{title:string;id:string};sites:Site[];accounts:Account[];errors:{source:string;message:string;accountId?:string}[];ga4AccessibleCount:number;leads:LeadStore}
export interface Period {start:string;end:string}
